name: Waka Readme

on:
    # for manual workflow trigger
    workflow_dispatch:
    schedule:
        # runs at 10 PM Almaty time (16:00 UTC)
        - cron: '0 16 * * *'

jobs:
    update-readme:
        name: WakaReadme DevMetrics
        runs-on: ubuntu-latest
        steps:
            # this action name
            - uses: athul/waka-readme@master # do NOT replace with anything else
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
                  ### meta
                  API_BASE_URL: https://wakatime.com/api # optional
                  ### content
                  SHOW_TITLE: true # optional
                  SECTION_NAME: waka # optional
                  #   BLOCKS: -> # optional
                  CODE_LANG: abap # optional
                  TIME_RANGE: last_30_days # optional
                  LANG_COUNT: 5 # optional
                  SHOW_TIME: true # optional
                  SHOW_TOTAL: true # optional
                  SHOW_MASKED_TIME: false # optional
                  SHOW_EDITORS: true        
                  SHOW_OS: true            
                  IGNORED_LANGUAGES: YAML JSON TOML # optional
                  ### commit
                  COMMIT_MESSAGE: updated coding metrics # optional
                  TARGET_BRANCH: main # optional
                  TARGET_PATH: README.md # optional
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
